version: "3"
services:
  db:
    image: mysql:5.7
    environment:
    - MYSQL_DATABASE=sample_db
    - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    tty: true
    restart:
      always
